### ISSUE TITLE
Ort-scan Error: no such option: "--performance"

### ISSUE THREAD

**Issue by karippery** [oss-review-toolkit/ort-ci-gitlab#16]
Hi,
  I got some errors while running the pipeline. 

**import Source Code to  my Gitlab**

Ort for Gitlab: `https://gitlab.com/tsteenbe/ort-gitlab-ci.git`
Ort-config:   `https://github.com/oss-review-toolkit/ort-config.git`
Mime-Types:  `https://gitlab.com/tsteenbe/mime-types.git`

**Variables I add to the pipeline are:**
   
SW_NAME: `Mime Types`
SW_VERSION: `2.1.35`
VCS_TYPE: `git`
VCS_URL: `shh://git@gitlab.com:Karippery/mime-types`
VCS_REVISION: `63435958fd26d94832b11cd916db1eaa06987f5e`
ORT_ALLOW_DYNAMIC_VERSIONS: `true`

**`.gitlab-ci.yml` in Mime Types**

```
include:
  - project: Karippery/ort-gitlab-ci
    file: ort-gitlab-ci.yml

image: node:latest

stages:
  - build
  - test
  - lint
  - ort-scan

cache:
  paths:
    - node_modules/

install-dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

unit-tests:
  stage: test
  script: npm test
  
lint:
  stage: test
  script: npm run lint

ort-scan:
  stage: ort-scan
  retry: 2
  variables:
    SW_NAME: "Mime Types"
    SW_VERSION: "2.1.27"
    VCS_URL: "ssh://git@gitlab.com:Karippery/mime-types.git"
    ORT_ALLOW_DYNAMIC_VERSIONS: "true"
  artifacts:
    reports:
      license_scanning: ort-results/gl-license-scanning-report.json

```
## ort-scan failed on mime type 

![mimeerror](https://user-images.githubusercontent.com/33422429/177392220-e97df2e4-fd01-4567-839f-e4819f1f36a7.PNG)

   [ show complete raw file is here raw.txt](https://github.com/oss-review-toolkit/ort-gitlab-ci/files/9048600/raw.txt)

## ort-scan failed in Ort for Gitlab

![ortcli](https://user-images.githubusercontent.com/33422429/177393061-b6b5f046-25ea-435b-a535-2fe5ec36cc14.PNG)

[ show complete raw file is here raw.txt](https://github.com/oss-review-toolkit/ort-gitlab-ci/files/9048687/raw.txt)

**metadata.json**

[metadata.json.txt](https://github.com/oss-review-toolkit/ort-gitlab-ci/files/9048696/metadata.json.txt)
 
 
 please help me to build ort tool
