### ISSUE TITLE
Ort-scan build failed in Mime types 

### ISSUE THREAD

**Issue by karippery** [oss-review-toolkit/ort-ci-gitlab#19]
Hello,
I trying to include .gitlab-ci.yml into mime types repository. 
 
 **Here is my .gitlab-ci.yml file** 
 
```
 include:
  - project: Karippery/ort-gitlab-ci
    file: ort-gitlab-ci.yml

image: node:latest

stages:
  - build
  - test
  - lint

cache:
  paths:
    - node_modules/

install-dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

unit-tests:
  stage: test
  script: npm test
  
lint:
  stage: test
  script: npm run lint

ort-scan:
  stage: test
  retry: 2
  variables:
    SW_NAME: "Mime Types"
    SW_VERSION: "2.1.32"
    VCS_URL: "https://gitlab.com/Karippery/mime-types.git"
    ORT_ALLOW_DYNAMIC_VERSIONS: "true"
  artifacts:
    reports:
      license_scanning: ort-results/gl-license-scanning-report.json
```
error I get 

![mimetype](https://user-images.githubusercontent.com/33422429/177525580-20eceefd-9688-4e52-a224-9828dd6a1641.PNG)

```
Executing busybox-1.35.0-r13.trigger
Executing ca-certificates-20211220-r0.trigger
OK: 9 MiB in 21 packages
[32;1m$ ORT_GITLAB_CI_REVISION=${OSS_GITLAB_CI_REVISION:-main} # collapsed multi-line command[0;m
curl: (22) The requested URL returned error: 401
section_end:1657101364:step_script
[0Ksection_start:1657101364:upload_artifacts_on_failure
[0K[0K[36;1mUploading artifacts for failed job[0;m[0;m
[32;1mUploading artifacts...[0;m
[0;33mWARNING: ort-results/scan-report-web-app.html: no matching files. Ensure that the artifact path is relative to the working directory[0;m 
[0;33mWARNING: ort-results: no matching files. Ensure that the artifact path is relative to the working directory[0;m 
[31;1mERROR: No files to upload                         [0;m 
[32;1mUploading artifacts...[0;m
[0;33mWARNING: ort-results/gl-license-scanning-report.json: no matching files. Ensure that the artifact path is relative to the working directory[0;m 
[31;1mERROR: No files to upload                         [0;m 
section_end:1657101365:upload_artifacts_on_failure
[0Ksection_start:1657101365:cleanup_file_variables
[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m
section_end:1657101366:cleanup_file_variables
[0K[31;1mERROR: Job failed: exit code 22
[0;m
```
